import { MigrationInterface, QueryRunner } from "typeorm";

export class InitSchema1778026650132 implements MigrationInterface {
    name = 'InitSchema1778026650132'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`warehouses\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(120) NOT NULL, \`address\` varchar(255) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`vehicle_makes\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(120) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`idx_vehicle_makes_name\` (\`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`brands\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(120) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`idx_brands_name\` (\`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`categories\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(120) NOT NULL, \`parentId\` varchar(36) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), INDEX \`idx_categories_name\` (\`name\`), INDEX \`idx_categories_parent\` (\`parentId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`suppliers\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(180) NOT NULL, \`taxId\` varchar(60) NULL, \`email\` varchar(180) NULL, \`phone\` varchar(30) NULL, \`address\` varchar(255) NULL, \`notes\` text NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), INDEX \`idx_suppliers_name\` (\`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`products\` (\`id\` varchar(36) NOT NULL, \`sku\` varchar(60) NOT NULL, \`partNumber\` varchar(80) NULL, \`barcode\` varchar(80) NULL, \`name\` varchar(200) NOT NULL, \`description\` text NULL, \`categoryId\` varchar(36) NULL, \`brandId\` varchar(36) NULL, \`supplierId\` varchar(36) NULL, \`cost\` decimal(15,2) NOT NULL DEFAULT '0.00', \`price\` decimal(15,2) NOT NULL DEFAULT '0.00', \`minStock\` int NOT NULL DEFAULT '0', \`maxStock\` int NULL, \`location\` varchar(120) NULL, \`isActive\` tinyint NOT NULL DEFAULT 1, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`idx_products_sku\` (\`sku\`), INDEX \`idx_products_part_number\` (\`partNumber\`), INDEX \`idx_products_barcode\` (\`barcode\`), INDEX \`idx_products_name\` (\`name\`), INDEX \`idx_products_category\` (\`categoryId\`), INDEX \`idx_products_brand\` (\`brandId\`), INDEX \`idx_products_supplier\` (\`supplierId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`vehicle_models\` (\`id\` varchar(36) NOT NULL, \`makeId\` varchar(36) NOT NULL, \`name\` varchar(120) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), INDEX \`idx_vehicle_models_make\` (\`makeId\`), UNIQUE INDEX \`uniq_vehicle_models_make_name\` (\`makeId\`, \`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`vehicle_fitments\` (\`id\` varchar(36) NOT NULL, \`productId\` varchar(36) NOT NULL, \`modelId\` varchar(36) NOT NULL, \`yearFrom\` smallint UNSIGNED NULL, \`yearTo\` smallint UNSIGNED NULL, INDEX \`idx_fitments_product_model\` (\`productId\`, \`modelId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`users\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(120) NOT NULL, \`email\` varchar(180) NOT NULL, \`passwordHash\` varchar(255) NOT NULL, \`role\` enum ('ADMIN') NOT NULL DEFAULT 'ADMIN', \`isActive\` tinyint NOT NULL DEFAULT 1, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`idx_users_email\` (\`email\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`stocks\` (\`id\` varchar(36) NOT NULL, \`productId\` varchar(36) NOT NULL, \`warehouseId\` varchar(36) NOT NULL, \`quantity\` int NOT NULL DEFAULT '0', \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), INDEX \`idx_stocks_product\` (\`productId\`), INDEX \`idx_stocks_warehouse\` (\`warehouseId\`), UNIQUE INDEX \`uniq_stocks_product_warehouse\` (\`productId\`, \`warehouseId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`customers\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(180) NOT NULL, \`taxId\` varchar(60) NULL, \`email\` varchar(180) NULL, \`phone\` varchar(30) NULL, \`address\` varchar(255) NULL, \`internalNotes\` text NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), INDEX \`idx_customers_name\` (\`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`quotation_items\` (\`id\` varchar(36) NOT NULL, \`quotationId\` varchar(36) NOT NULL, \`productId\` varchar(36) NOT NULL, \`qty\` int NOT NULL, \`unitPrice\` decimal(15,2) NOT NULL, \`discount\` decimal(15,2) NOT NULL DEFAULT '0.00', \`subtotal\` decimal(15,2) NOT NULL, INDEX \`idx_quotation_items_quotation\` (\`quotationId\`), INDEX \`idx_quotation_items_product\` (\`productId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`quotations\` (\`id\` varchar(36) NOT NULL, \`number\` varchar(40) NOT NULL, \`customerId\` varchar(36) NOT NULL, \`date\` datetime(6) NOT NULL, \`validUntil\` datetime(6) NULL, \`status\` enum ('DRAFT', 'SENT', 'APPROVED', 'REJECTED', 'CONVERTED', 'EXPIRED') NOT NULL DEFAULT 'DRAFT', \`total\` decimal(15,2) NOT NULL DEFAULT '0.00', \`notes\` text NULL, \`userId\` varchar(36) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`idx_quotations_number\` (\`number\`), INDEX \`idx_quotations_customer\` (\`customerId\`), INDEX \`idx_quotations_date\` (\`date\`), INDEX \`idx_quotations_status\` (\`status\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`sale_items\` (\`id\` varchar(36) NOT NULL, \`saleId\` varchar(36) NOT NULL, \`productId\` varchar(36) NOT NULL, \`qty\` int NOT NULL, \`unitPrice\` decimal(15,2) NOT NULL, \`discount\` decimal(15,2) NOT NULL DEFAULT '0.00', \`subtotal\` decimal(15,2) NOT NULL, \`unitCost\` decimal(15,2) NOT NULL, INDEX \`idx_sale_items_sale\` (\`saleId\`), INDEX \`idx_sale_items_product\` (\`productId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`sales\` (\`id\` varchar(36) NOT NULL, \`number\` varchar(40) NOT NULL, \`customerId\` varchar(36) NOT NULL, \`date\` datetime(6) NOT NULL, \`total\` decimal(15,2) NOT NULL DEFAULT '0.00', \`paymentMethod\` enum ('CASH', 'TRANSFER', 'CARD') NOT NULL, \`status\` enum ('PENDING', 'PAID', 'CANCELLED') NOT NULL DEFAULT 'PENDING', \`quotationId\` varchar(36) NULL, \`userId\` varchar(36) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`idx_sales_number\` (\`number\`), INDEX \`idx_sales_customer\` (\`customerId\`), INDEX \`idx_sales_date\` (\`date\`), INDEX \`idx_sales_status\` (\`status\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`purchase_entry_items\` (\`id\` varchar(36) NOT NULL, \`entryId\` varchar(36) NOT NULL, \`productId\` varchar(36) NOT NULL, \`qty\` int NOT NULL, \`unitCost\` decimal(15,2) NOT NULL, \`subtotal\` decimal(15,2) NOT NULL, INDEX \`idx_purchase_items_entry\` (\`entryId\`), INDEX \`idx_purchase_items_product\` (\`productId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`purchase_entries\` (\`id\` varchar(36) NOT NULL, \`supplierId\` varchar(36) NOT NULL, \`date\` datetime(6) NOT NULL, \`total\` decimal(15,2) NOT NULL DEFAULT '0.00', \`notes\` text NULL, \`userId\` varchar(36) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), INDEX \`idx_purchase_entries_supplier\` (\`supplierId\`), INDEX \`idx_purchase_entries_date\` (\`date\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`inventory_movements\` (\`id\` varchar(36) NOT NULL, \`productId\` varchar(36) NOT NULL, \`warehouseId\` varchar(36) NOT NULL, \`type\` enum ('PURCHASE_IN', 'SALE_OUT', 'ADJUSTMENT', 'RETURN_IN', 'RETURN_OUT') NOT NULL, \`qty\` int NOT NULL, \`unitCost\` decimal(15,2) NULL, \`reference\` varchar(40) NULL, \`refId\` char(36) NULL, \`userId\` varchar(36) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), INDEX \`idx_movements_product\` (\`productId\`), INDEX \`idx_movements_warehouse\` (\`warehouseId\`), INDEX \`idx_movements_type\` (\`type\`), INDEX \`idx_movements_ref\` (\`refId\`), INDEX \`idx_movements_created_at\` (\`createdAt\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`expense_categories\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(120) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`idx_expense_categories_name\` (\`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`company_settings\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(180) NOT NULL, \`address\` varchar(255) NULL, \`phone\` varchar(30) NULL, \`email\` varchar(180) NULL, \`taxId\` varchar(60) NULL, \`logoUrl\` varchar(500) NULL, \`currency\` varchar(8) NOT NULL DEFAULT 'USD', \`quotationFooter\` text NULL, \`defaultValidityDays\` int NOT NULL DEFAULT '15', \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`cash_transactions\` (\`id\` varchar(36) NOT NULL, \`date\` datetime(6) NOT NULL, \`type\` enum ('INCOME', 'EXPENSE') NOT NULL, \`source\` enum ('SALE', 'PURCHASE', 'MANUAL') NOT NULL, \`sourceId\` char(36) NULL, \`description\` varchar(255) NULL, \`amount\` decimal(15,2) NOT NULL, \`paymentMethod\` enum ('CASH', 'TRANSFER', 'CARD') NOT NULL, \`expenseCategoryId\` varchar(36) NULL, \`isVoided\` tinyint NOT NULL DEFAULT 0, \`userId\` varchar(36) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), INDEX \`idx_cash_tx_date\` (\`date\`), INDEX \`idx_cash_tx_type\` (\`type\`), INDEX \`idx_cash_tx_source\` (\`source\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`categories\` ADD CONSTRAINT \`FK_9a6f051e66982b5f0318981bcaa\` FOREIGN KEY (\`parentId\`) REFERENCES \`categories\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD CONSTRAINT \`FK_ff56834e735fa78a15d0cf21926\` FOREIGN KEY (\`categoryId\`) REFERENCES \`categories\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD CONSTRAINT \`FK_ea86d0c514c4ecbb5694cbf57df\` FOREIGN KEY (\`brandId\`) REFERENCES \`brands\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD CONSTRAINT \`FK_c143cbc0299e1f9220c4b5debd8\` FOREIGN KEY (\`supplierId\`) REFERENCES \`suppliers\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`vehicle_models\` ADD CONSTRAINT \`FK_d2ec9cc9ea521d4cfeee631c92a\` FOREIGN KEY (\`makeId\`) REFERENCES \`vehicle_makes\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`vehicle_fitments\` ADD CONSTRAINT \`FK_2d2844bfd841ecddaf12de9a55a\` FOREIGN KEY (\`productId\`) REFERENCES \`products\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`vehicle_fitments\` ADD CONSTRAINT \`FK_4b0b5ed7496777bf47fbc3ec9fd\` FOREIGN KEY (\`modelId\`) REFERENCES \`vehicle_models\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`stocks\` ADD CONSTRAINT \`FK_3024bbca6232c8b6efa3ff51028\` FOREIGN KEY (\`productId\`) REFERENCES \`products\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`stocks\` ADD CONSTRAINT \`FK_08a4e40be97ec3788a218169ef1\` FOREIGN KEY (\`warehouseId\`) REFERENCES \`warehouses\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`quotation_items\` ADD CONSTRAINT \`FK_daed37b90fdb61300eabb8e2743\` FOREIGN KEY (\`quotationId\`) REFERENCES \`quotations\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`quotation_items\` ADD CONSTRAINT \`FK_8e92de26635dda771136a35863d\` FOREIGN KEY (\`productId\`) REFERENCES \`products\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`quotations\` ADD CONSTRAINT \`FK_116e4084cf9a95beea7e502ac0d\` FOREIGN KEY (\`customerId\`) REFERENCES \`customers\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`quotations\` ADD CONSTRAINT \`FK_9acdd6f9d1e07a9e3b0fb1e6d65\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sale_items\` ADD CONSTRAINT \`FK_c642be08de5235317d4cf3deb40\` FOREIGN KEY (\`saleId\`) REFERENCES \`sales\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sale_items\` ADD CONSTRAINT \`FK_d675aea38a16313e844662c48f8\` FOREIGN KEY (\`productId\`) REFERENCES \`products\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sales\` ADD CONSTRAINT \`FK_3a92cf6add00043cef9833db1cd\` FOREIGN KEY (\`customerId\`) REFERENCES \`customers\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sales\` ADD CONSTRAINT \`FK_9c88cbfc41718ee9455deff6a4b\` FOREIGN KEY (\`quotationId\`) REFERENCES \`quotations\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sales\` ADD CONSTRAINT \`FK_52ff6cd9431cc7687c76f935938\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`purchase_entry_items\` ADD CONSTRAINT \`FK_205af65c03aeb6ef11e1cf0b21e\` FOREIGN KEY (\`entryId\`) REFERENCES \`purchase_entries\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`purchase_entry_items\` ADD CONSTRAINT \`FK_e9246f619f218a0c0afc7199ef4\` FOREIGN KEY (\`productId\`) REFERENCES \`products\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`purchase_entries\` ADD CONSTRAINT \`FK_0fa18f775c726ec2f5e22c5bbf1\` FOREIGN KEY (\`supplierId\`) REFERENCES \`suppliers\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`purchase_entries\` ADD CONSTRAINT \`FK_81b237490adb0a8a143beb552f7\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`inventory_movements\` ADD CONSTRAINT \`FK_05715a7ea47e49653f164c0dd8c\` FOREIGN KEY (\`productId\`) REFERENCES \`products\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`inventory_movements\` ADD CONSTRAINT \`FK_f5e2a192d8b645f5d49fd0acae3\` FOREIGN KEY (\`warehouseId\`) REFERENCES \`warehouses\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`inventory_movements\` ADD CONSTRAINT \`FK_7fd6b141c027be66629d76f26b7\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cash_transactions\` ADD CONSTRAINT \`FK_eec8570ec0c6047418247070013\` FOREIGN KEY (\`expenseCategoryId\`) REFERENCES \`expense_categories\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cash_transactions\` ADD CONSTRAINT \`FK_70bb2f49b4bb16ec3ef3d1ba47e\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`cash_transactions\` DROP FOREIGN KEY \`FK_70bb2f49b4bb16ec3ef3d1ba47e\``);
        await queryRunner.query(`ALTER TABLE \`cash_transactions\` DROP FOREIGN KEY \`FK_eec8570ec0c6047418247070013\``);
        await queryRunner.query(`ALTER TABLE \`inventory_movements\` DROP FOREIGN KEY \`FK_7fd6b141c027be66629d76f26b7\``);
        await queryRunner.query(`ALTER TABLE \`inventory_movements\` DROP FOREIGN KEY \`FK_f5e2a192d8b645f5d49fd0acae3\``);
        await queryRunner.query(`ALTER TABLE \`inventory_movements\` DROP FOREIGN KEY \`FK_05715a7ea47e49653f164c0dd8c\``);
        await queryRunner.query(`ALTER TABLE \`purchase_entries\` DROP FOREIGN KEY \`FK_81b237490adb0a8a143beb552f7\``);
        await queryRunner.query(`ALTER TABLE \`purchase_entries\` DROP FOREIGN KEY \`FK_0fa18f775c726ec2f5e22c5bbf1\``);
        await queryRunner.query(`ALTER TABLE \`purchase_entry_items\` DROP FOREIGN KEY \`FK_e9246f619f218a0c0afc7199ef4\``);
        await queryRunner.query(`ALTER TABLE \`purchase_entry_items\` DROP FOREIGN KEY \`FK_205af65c03aeb6ef11e1cf0b21e\``);
        await queryRunner.query(`ALTER TABLE \`sales\` DROP FOREIGN KEY \`FK_52ff6cd9431cc7687c76f935938\``);
        await queryRunner.query(`ALTER TABLE \`sales\` DROP FOREIGN KEY \`FK_9c88cbfc41718ee9455deff6a4b\``);
        await queryRunner.query(`ALTER TABLE \`sales\` DROP FOREIGN KEY \`FK_3a92cf6add00043cef9833db1cd\``);
        await queryRunner.query(`ALTER TABLE \`sale_items\` DROP FOREIGN KEY \`FK_d675aea38a16313e844662c48f8\``);
        await queryRunner.query(`ALTER TABLE \`sale_items\` DROP FOREIGN KEY \`FK_c642be08de5235317d4cf3deb40\``);
        await queryRunner.query(`ALTER TABLE \`quotations\` DROP FOREIGN KEY \`FK_9acdd6f9d1e07a9e3b0fb1e6d65\``);
        await queryRunner.query(`ALTER TABLE \`quotations\` DROP FOREIGN KEY \`FK_116e4084cf9a95beea7e502ac0d\``);
        await queryRunner.query(`ALTER TABLE \`quotation_items\` DROP FOREIGN KEY \`FK_8e92de26635dda771136a35863d\``);
        await queryRunner.query(`ALTER TABLE \`quotation_items\` DROP FOREIGN KEY \`FK_daed37b90fdb61300eabb8e2743\``);
        await queryRunner.query(`ALTER TABLE \`stocks\` DROP FOREIGN KEY \`FK_08a4e40be97ec3788a218169ef1\``);
        await queryRunner.query(`ALTER TABLE \`stocks\` DROP FOREIGN KEY \`FK_3024bbca6232c8b6efa3ff51028\``);
        await queryRunner.query(`ALTER TABLE \`vehicle_fitments\` DROP FOREIGN KEY \`FK_4b0b5ed7496777bf47fbc3ec9fd\``);
        await queryRunner.query(`ALTER TABLE \`vehicle_fitments\` DROP FOREIGN KEY \`FK_2d2844bfd841ecddaf12de9a55a\``);
        await queryRunner.query(`ALTER TABLE \`vehicle_models\` DROP FOREIGN KEY \`FK_d2ec9cc9ea521d4cfeee631c92a\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP FOREIGN KEY \`FK_c143cbc0299e1f9220c4b5debd8\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP FOREIGN KEY \`FK_ea86d0c514c4ecbb5694cbf57df\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP FOREIGN KEY \`FK_ff56834e735fa78a15d0cf21926\``);
        await queryRunner.query(`ALTER TABLE \`categories\` DROP FOREIGN KEY \`FK_9a6f051e66982b5f0318981bcaa\``);
        await queryRunner.query(`DROP INDEX \`idx_cash_tx_source\` ON \`cash_transactions\``);
        await queryRunner.query(`DROP INDEX \`idx_cash_tx_type\` ON \`cash_transactions\``);
        await queryRunner.query(`DROP INDEX \`idx_cash_tx_date\` ON \`cash_transactions\``);
        await queryRunner.query(`DROP TABLE \`cash_transactions\``);
        await queryRunner.query(`DROP TABLE \`company_settings\``);
        await queryRunner.query(`DROP INDEX \`idx_expense_categories_name\` ON \`expense_categories\``);
        await queryRunner.query(`DROP TABLE \`expense_categories\``);
        await queryRunner.query(`DROP INDEX \`idx_movements_created_at\` ON \`inventory_movements\``);
        await queryRunner.query(`DROP INDEX \`idx_movements_ref\` ON \`inventory_movements\``);
        await queryRunner.query(`DROP INDEX \`idx_movements_type\` ON \`inventory_movements\``);
        await queryRunner.query(`DROP INDEX \`idx_movements_warehouse\` ON \`inventory_movements\``);
        await queryRunner.query(`DROP INDEX \`idx_movements_product\` ON \`inventory_movements\``);
        await queryRunner.query(`DROP TABLE \`inventory_movements\``);
        await queryRunner.query(`DROP INDEX \`idx_purchase_entries_date\` ON \`purchase_entries\``);
        await queryRunner.query(`DROP INDEX \`idx_purchase_entries_supplier\` ON \`purchase_entries\``);
        await queryRunner.query(`DROP TABLE \`purchase_entries\``);
        await queryRunner.query(`DROP INDEX \`idx_purchase_items_product\` ON \`purchase_entry_items\``);
        await queryRunner.query(`DROP INDEX \`idx_purchase_items_entry\` ON \`purchase_entry_items\``);
        await queryRunner.query(`DROP TABLE \`purchase_entry_items\``);
        await queryRunner.query(`DROP INDEX \`idx_sales_status\` ON \`sales\``);
        await queryRunner.query(`DROP INDEX \`idx_sales_date\` ON \`sales\``);
        await queryRunner.query(`DROP INDEX \`idx_sales_customer\` ON \`sales\``);
        await queryRunner.query(`DROP INDEX \`idx_sales_number\` ON \`sales\``);
        await queryRunner.query(`DROP TABLE \`sales\``);
        await queryRunner.query(`DROP INDEX \`idx_sale_items_product\` ON \`sale_items\``);
        await queryRunner.query(`DROP INDEX \`idx_sale_items_sale\` ON \`sale_items\``);
        await queryRunner.query(`DROP TABLE \`sale_items\``);
        await queryRunner.query(`DROP INDEX \`idx_quotations_status\` ON \`quotations\``);
        await queryRunner.query(`DROP INDEX \`idx_quotations_date\` ON \`quotations\``);
        await queryRunner.query(`DROP INDEX \`idx_quotations_customer\` ON \`quotations\``);
        await queryRunner.query(`DROP INDEX \`idx_quotations_number\` ON \`quotations\``);
        await queryRunner.query(`DROP TABLE \`quotations\``);
        await queryRunner.query(`DROP INDEX \`idx_quotation_items_product\` ON \`quotation_items\``);
        await queryRunner.query(`DROP INDEX \`idx_quotation_items_quotation\` ON \`quotation_items\``);
        await queryRunner.query(`DROP TABLE \`quotation_items\``);
        await queryRunner.query(`DROP INDEX \`idx_customers_name\` ON \`customers\``);
        await queryRunner.query(`DROP TABLE \`customers\``);
        await queryRunner.query(`DROP INDEX \`uniq_stocks_product_warehouse\` ON \`stocks\``);
        await queryRunner.query(`DROP INDEX \`idx_stocks_warehouse\` ON \`stocks\``);
        await queryRunner.query(`DROP INDEX \`idx_stocks_product\` ON \`stocks\``);
        await queryRunner.query(`DROP TABLE \`stocks\``);
        await queryRunner.query(`DROP INDEX \`idx_users_email\` ON \`users\``);
        await queryRunner.query(`DROP TABLE \`users\``);
        await queryRunner.query(`DROP INDEX \`idx_fitments_product_model\` ON \`vehicle_fitments\``);
        await queryRunner.query(`DROP TABLE \`vehicle_fitments\``);
        await queryRunner.query(`DROP INDEX \`uniq_vehicle_models_make_name\` ON \`vehicle_models\``);
        await queryRunner.query(`DROP INDEX \`idx_vehicle_models_make\` ON \`vehicle_models\``);
        await queryRunner.query(`DROP TABLE \`vehicle_models\``);
        await queryRunner.query(`DROP INDEX \`idx_products_supplier\` ON \`products\``);
        await queryRunner.query(`DROP INDEX \`idx_products_brand\` ON \`products\``);
        await queryRunner.query(`DROP INDEX \`idx_products_category\` ON \`products\``);
        await queryRunner.query(`DROP INDEX \`idx_products_name\` ON \`products\``);
        await queryRunner.query(`DROP INDEX \`idx_products_barcode\` ON \`products\``);
        await queryRunner.query(`DROP INDEX \`idx_products_part_number\` ON \`products\``);
        await queryRunner.query(`DROP INDEX \`idx_products_sku\` ON \`products\``);
        await queryRunner.query(`DROP TABLE \`products\``);
        await queryRunner.query(`DROP INDEX \`idx_suppliers_name\` ON \`suppliers\``);
        await queryRunner.query(`DROP TABLE \`suppliers\``);
        await queryRunner.query(`DROP INDEX \`idx_categories_parent\` ON \`categories\``);
        await queryRunner.query(`DROP INDEX \`idx_categories_name\` ON \`categories\``);
        await queryRunner.query(`DROP TABLE \`categories\``);
        await queryRunner.query(`DROP INDEX \`idx_brands_name\` ON \`brands\``);
        await queryRunner.query(`DROP TABLE \`brands\``);
        await queryRunner.query(`DROP INDEX \`idx_vehicle_makes_name\` ON \`vehicle_makes\``);
        await queryRunner.query(`DROP TABLE \`vehicle_makes\``);
        await queryRunner.query(`DROP TABLE \`warehouses\``);
    }

}
